version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: mongodb13
    ports:
      - 27017:27017
    volumes:
      - "mongodb_data:/data/db"
  backend:
    image: "backend24"
    container_name: simple_backend_application
    ports:
      - 3000:3000
      - 4000:3000
    environment:
       MONGO_URL: "localhost:0.0.0.0://mongodb13:27017"
volumes:
  mongodb_data:
